version: '3'

services:

  worker-1:
    image: pushshift-cluster-template:latest
    environment:
      - EXEC_TYPE=COMMENTS
      - SDATE=2021-07-01
      - EDATE=2021-08-01

  worker-2:
    image: pushshift-cluster-template:latest
    environment:
      - EXEC_TYPE=COMMENTS
      - SDATE=2021-08-01
      - EDATE=2021-09-01
